### PR TITLE
fix: Interface child items had incorrect reference

### PR DESCRIPTION
**Pull request by GNewbury1**

### CODE REVIEW

**Comment by vaerh** [comment]
I just wanted to discuss the different resource naming in our versions. I have shortened some of the name. Maybe it makes sense for these resources to make a double naming?
https://github.com/GNewbury1/terraform-provider-routeros/blob/1ebca01793f8d423fbcc2fee33ae2de5dbc98a08/routeros/provider.go#L78-L85

**Comment by GNewbury1** [comment]
> I just wanted to discuss the different resource naming in our versions. I have shortened some of the name. Maybe it makes sense for these resources to make a double naming?
> 
> https://github.com/GNewbury1/terraform-provider-routeros/blob/1ebca01793f8d423fbcc2fee33ae2de5dbc98a08/routeros/provider.go#L78-L85

Actually yeah, that's a good idea. Gimme a sec and I'll push the change for you to review

**Comment by GNewbury1** [comment]
How does that look? Added some comments so we don't forget why we did this :P

**Review by vaerh — APPROVED** [review]
Exactly what is needed!

**Pull request merged**
